{
 "title": "Triton Service System Overview",
 "description": "Triton Service System Overview",
 "tags": [ "triton" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datacenter", "label": "Datacenter", "query": "cpu_sys_usage" },
   {
    "name": "triton_service",
    "label": "Triton Service",
    "query": "cpu_sys_usage{job=~\"admin_.*\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Instance Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(time_of_day{alias=~\"[[triton_service:regex]].\"})"
    }
   ]
  },
  {
   "title": "cpu cap: cores provisioned",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(cpucap_limit_percentage{alias=~\"[[triton_service:regex]].\"}) / 100"
    }
   ]
  },
  {
   "title": "Total DRAM Provisioned",
   "type": "singlestat",
   "description": "Total DRAM provisioned for Triton Services",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(mem_limit{alias=~\"[[triton_service:regex]][0-9]+\"})"
    }
   ]
  },
  {
   "title": "Total ZFS Used",
   "type": "singlestat",
   "description": "Total ZFS Used by Triton",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(zfs_used{alias=~\"[[triton_service:regex]][0-9]+\"})"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "description": "(user + system time)",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "((increase(cpu_sys_usage{alias=~\"[[triton_service:regex]][0-9]+\"}[60s]) + increase(cpu_user_usage{alias=~\"[[triton_service:regex]][0-9]+\"}[60s])) / 60000000000)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "load_average{alias=~\"[[triton_service:regex]][0-9]+\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "% of cpu_cap",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "cpucap_cur_usage_percentage{alias=~\"[[triton_service:regex]][0-9]+\"} / cpucap_effective_percentage{alias=~\"[[triton_service:regex]][0-9]+\"} \n",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "cpu_user_usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "((increase(cpu_user_usage{alias=~\"[[triton_service:regex]][0-9]+\"}[60s])) / 60000000000)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "cpu_sys_usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "((increase(cpu_sys_usage{alias=~\"[[triton_service:regex]][0-9]+\"}[60s])) / 60000000000)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "cpu_wait_time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "((increase(cpu_wait_time{alias=~\"[[triton_service:regex]][0-9]+\"}[60s])) / 60000000000)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mem_agg_usage{alias=~\"[[triton_service:regex]][0-9]+\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "memory vs cap %",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "mem_agg_usage{alias=~\"[[triton_service:regex]][0-9]+\"} / mem_limit{alias=~\"[[triton_service:regex]][0-9]+\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "swap vs cap %",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "mem_swap{alias=~\"[[triton_service:regex]][0-9]+\"} / mem_swap_limit{alias=~\"[[triton_service:regex]][0-9]+\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(increase(net_agg_bytes_out{alias=~\"[[triton_service:regex]][0-9]+\"}[60s]) / 60)",
     "legendFormat": "Out - {{alias}}"
    },
    {
     "expr": "(increase(net_agg_bytes_in{alias=~\"[[triton_service:regex]][0-9]+\"}[60s]) / 60)",
     "legendFormat": "In - {{alias}}"
    }
   ]
  },
  {
   "title": "RX Packets Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(net_agg_packets_in{alias=~\"[[triton_service:regex]][0-9]+\"}[60s]) / 60",
     "legendFormat": "{{alias}} - {{interface}}"
    }
   ]
  },
  {
   "title": "TX Packets Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(net_agg_packets_out{alias=~\"[[triton_service:regex]][0-9]+\"}[60s]) / 60",
     "legendFormat": "{{alias}} - {{interface}}"
    }
   ]
  },
  {
   "title": "TCP Retransmit Segments",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 62 },
   "yaxes": [
    { "format": "short", "label": "Seg/Sec" }
   ],
   "targets": [
    {
     "expr": "increase(tcp_retransmitted_segment_count{alias=~\"[[triton_service:regex]][0-9]+\"}[60s]) / 60",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "tcp_current_established_connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tcp_current_established_connections_total{alias=~\"[[triton_service:regex]][0-9]+\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "tcp_duplicate_ack",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 70 },
   "yaxes": [
    { "format": "short", "label": "con/s" }
   ],
   "targets": [
    {
     "expr": "increase(tcp_duplicate_ack_count{alias=~\"[[triton_service:regex]][0-9]+\"}[60s]) / 60",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "tcp_listen_drop",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 70 },
   "yaxes": [
    { "format": "short", "label": "con/s" }
   ],
   "targets": [
    {
     "expr": "increase(tcp_listen_drop_count{alias=~\"[[triton_service:regex]][0-9]+\"}[60s]) / 60",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "tcp_failed_connection_attempt",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short", "label": "con/s" }
   ],
   "targets": [
    {
     "expr": "increase(tcp_failed_connection_attempt_count{alias=~\"[[triton_service:regex]][0-9]+\"}[60s]) / 60",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "tcp_passive_open_count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(tcp_passive_open_count{alias=~\"[[triton_service:regex]][0-9]+\"}[60s]) / 60",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "tcp_active_open",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(tcp_active_open_count{alias=~\"[[triton_service:regex]][0-9]+\"}[60s]) / 60",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "ZFS Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "zfs_used{alias=~\"[[triton_service:regex]][0-9]+\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "ZFS Used / Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "zfs_used{alias=~\"[[triton_service:regex]][0-9]+\"} / (zfs_used{alias=~\"[[triton_service:regex]][0-9]+\"} + zfs_available{alias=~\"[[triton_service:regex]][0-9]+\"})",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "VFS Wait Length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "(increase(vfs_wait_length_time_count{alias=~\"[[triton_service:regex]][0-9]+\"}[60s]) / 60)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "VFS Wait States",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vfs_elements_wait_state{alias=~\"[[triton_service:regex]][0-9]+\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "vfs_read_operation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(vfs_read_operation_count{alias=~\"[[triton_service:regex]][0-9]+\"}[60s]) / 60",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "vfs_bytes_read/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 98 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(vfs_bytes_read_count{alias=~\"[[triton_service:regex]][0-9]+\"}[60s]) / 60",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "vfs_write_operation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(vfs_write_operation_count{alias=~\"[[triton_service:regex]][0-9]+\"}[60s]) / 60",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "vfs_bytes_written/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 98 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(vfs_bytes_written_count{alias=~\"[[triton_service:regex]][0-9]+\"}[60s]) / 60",
     "legendFormat": "{{alias}}"
    }
   ]
  }
 ]
}