global:
  scrape_interval: 5s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "fastapi"
    static_configs:
      - targets: ["api:8000"]

  - job_name: "triton"
    static_configs:
      - targets: ["triton:8002"]